# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

find_nn_corr_internal <- function(corrMat, m) {
    .Call('_nntmvn_find_nn_corr_internal', PACKAGE = 'nntmvn', corrMat, m)
}

